### ISSUE TITLE
For some users, channel_shuffle_gui does not run from their user folder

### ISSUE THREAD

**Issue by lukors** [lukors/channel_shuffle#1]
Source: http://www.polycount.com/forum/showpost.php?p=2239253&postcount=3

> During first startup directly from my windows downloads folder it would it would take some while, then a cmd-window showed up, no gui though. Used task managed to close the channel_shuffle.exe(I think it was?). Then it reappeared along with the GUI interface. I tried closing it a few times but reappeared a few more times. Finally got it closed.
> 
> Moved the whole extracted folder to c:/ and it worked better. Moving it back to the downloads folder reproduces this weird behaviour. It doesn't show the GUI but rather just the CMD-window and keeps closing and reopening itself? Two instances of "channel_shuffle.exe" seem to show up in my task manager.
> 
> Anyways, when running it from C:/ it shows up fine. Loads images fine and lets me swizzle them around with preview windows working correctly. ~~However the drag-drop to save doesn't seem to work properly for me. It creates an "untitled.tga", but it's all black. Disabled both my AV and FW software and made sure to run the application as admin but to no success. I'm running Win7 64bit.~~
> 
> ![When running from Downloads-folder. Keeps opening and closing that CMD-window by itself. Had to quickly close down both "channel_shuffle.exe" instances to get it to stop.](http://imageshack.com/a/img661/9490/GfXnGn.jpg)

**Comment by autious** [comment]
Sounds like it might be related to folder depth or folder with spaces in the name.

**Comment by lukors** [comment]
There is nothing extraordinary about the folder depth (he's just 5 folders deep), and it works fine for me from my downloads dir that has both a space and an ä in the path.

It might have something to do with his temp directory where all generated images are saved. Something seems to be causing the CLI version to freeze when generating the images. I guess it could be a folder depth thing if his temp folder is located somewhere very, very deep.

It's weird that cmd windows are popping up, because I was fairly sure they shouldn't do that when I launch the CLI application in a QProcess as opposed to using QProcess::startDetached() (which causes those cmd windows to briefly pop up for me when the program is run).

**Comment by autious** [comment]
Interesting, is he running a different version of windows from the dev computer?

**Comment by lukors** [comment]
Interesting indeed! One of the dev computers is Win8, the other is Win7, works on both for me.

**Comment by lukors** [comment]
The image he provided (show in original post) show channel_shuffle.exe using 48MB of RAM, which is huge, it should only really tops use about as much RAM as the images it holds plus the output image.

The default images that come with the application are 256x256, so that should only be about 0.6MB.. Hmm...

**Comment by lukors** [comment]
I added #3 and packed that as a release and sent to the person who had the issue, hopefully this will reveal what is going wrong.

**Comment by lukors** [comment]
Did some testing on his computer. Apparently the condition that needs to be met for this to happen is that the program needs to be located in his user folder. Will continue to do more testing soon.

**Comment by autious** [comment]
Does he have wierd accents in his username? like ÄÅÖü or Hangul or similar?

**Comment by lukors** [comment]
Nope, no spaces or even caps letters even.
It might have something to do with some security thing in Windows maybe? But it sounded like he had tried turning them all off.

What makes it even more weird is that he had moved the application folder to C: and used it there and it worked. Later he moved it back to the Downloads dir, and then it worked to start the application there. So he removed it from there and unpacked it again in the Downloads dir and the newly unpacked one doesn't work. The contents of the application folder does not change at any point, it's just exes, dlls, a readme, a bat file and some default images. What is going on?

Could it have to do with permissions? Only reading is ever done from that directory though.

**Comment by lukors** [comment]
By the way, the thing about the image being black was a false alarm, the image just had a black alpha channel because the input images had no alpha channel. Recently committed a fix for this to the CLI version that defaults to a value of 255 for the alpha channel instead of 0 as for the other channels.

**Comment by lukors** [comment]
Turned out to be antivirus after all, Avast!

It was scanning the CLI version each time it was run by the GUI verison, which is like 21 times or something like that.
