### ISSUE TITLE
Inform about supported image formats when an unsupported image is opened

### ISSUE THREAD

**Issue by lukors** [lukors/channel_shuffle#4]
Could happen through a pop-up showing supported file formats. If you attempt to load a file with a supported file ending, but it still can't be loaded, show a more detailed description of what is and what isn't supported in that specific format so the user can fix it.

**Comment by autious** [comment]
If it's possible to solve without a popup while maintaining expected behaviour for a GUI  application it might be preferable and in line with program design.

**Comment by lukors** [comment]
I would like to make better use of the status bar at some point to show messages like this, but for a first iteration of this enhancement pop-ups will get the job done.

**Comment by lukors** [comment]
That is unless someone else would like to do create a system to relay messages through the status bar of course. :)

I'm thinking a system like the one Blender has where you can send warnings, errors and information through it and they will show up in different colors. There would also need to be a way to display messages that are longer than the bar. I feel like that's non-intrusive and flexible enough.

This is a bit off topic though, if anyone feels up for it they can create a task for it and start programming!

**Comment by lukors** [comment]
Got a basic implementation finished, this will do for now.
