### ISSUE TITLE
Feature Request: 4 source images

### ISSUE THREAD

**Issue by WarnerV** [lukors/channel_shuffle#8]
For game engines, you often need to 'pack' 4 channels into 1 texture (Roughness, Metallic, Height information, etc..)

This tool could be very useful for that operation: if you can just drag the various source images and create the output.

Any change the tool can be developed to allow this?

**Comment by lukors** [comment]
Hey!

I didn't see your comment until now.

I've expanded my horizons and am working on much more general, node based application that can do all that Channel Shuffle can, and much more. I'm calling it `Kanter`. I'm not going to update Channel Shuffle anymore.

I'm currently working on the GUI. Here is the repository for that if you're interested, though it hasn't gotten to a working state yet: https://github.com/lukors/kanter

**Comment by lukors** [comment]
The tool at the link now allows for the functionality you describe, though no drag and drop yet. So I'm closing this issue.
